/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        Mobile myPhone = new Mobile();
        Iphone apple = new Iphone();
        Android graysAndroid = new Android();
        myPhone.call("This is a message");
        apple.call("Apple Message");
        graysAndroid.call("Android Message");

        //show specs
        myPhone.setBrand("Android");
        myPhone.setColor("Red");
        myPhone.setName("Gray");
        myPhone.showSpecs();

        Person gray = new Person();
        gray.setName("Gray");
        gray.setMyMobile(graysAndroid);
        gray.getMyMobile().call("Gray's Androidsfdgjskfksfdkdv");
        gray.getMyMobile().call("Gray's Android");

        IphoneRobot robot = new IphoneRobot();
        robot.setMobile(graysAndroid);

    }
}
