/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        Mobile myPhone = new Mobile();
        Iphone graysIphone = new Iphone();
        Android graysAndroid = new Android();
        myPhone.call("This is a message");
        graysIphone.call("Apple Message");
        graysAndroid.call("Android Message");

        //show specs
        myPhone.setBrand("Android");
        myPhone.setColor("Red");
        myPhone.setName("Gray");
        myPhone.showSpecs();

        Person gray = new Person();
        gray.setName("Gray");
        gray.setMyMobile(graysAndroid);
        gray.makeCall("this will be sent");
        gray.makeCall("this is too long to send for Android");

        gray.setMyMobile(graysIphone);
        gray.makeCall("this will be sent");
        gray.makeCall("this is too long to send for Iphone");

        IphoneRobot robot = new IphoneRobot();
        robot.setMobile(graysAndroid);

    }
}
